graph LR
    main_1 -->|push message| in_r1
    out_r1 --> |r1.take| block_r2
    out_r2 --> |pull message| main_2

    subgraph Ractor: r1
        in_r1 --> queue_r1
        queue_r1 --> block_r1
        block_r1 --> out_r1

        in_r1(in port)
        queue_r1(mailbox)
        block_r1("code <br>Ractor.yield(Ractor.receive))")
        out_r1
    end

    subgraph Ractor: r2
        queue_r2 -.-> block_r2
        in_r2 -.-> queue_r2
        block_r2 --> out_r2

        in_r2
        queue_r2(mailbox)
        block_r2("code<br>Ractor.yield(r1.take)")
        out_r2
    end

    subgraph Ractor: main
        inport_main -.-> queue_main
        queue_main -.-> main_1
        main_1 -.-> main_2
        main_2 -.-> outport_main

        inport_main(in port)

        main_1("code<br>r1.send 1")
        main_2("code<br>r2.take")
    end
